/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockInRouteImport } from './routes/stock-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as FactoriesRouteImport } from './routes/factories'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CustomerPricesRouteImport } from './routes/customer-prices'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerPricesSetupRouteImport } from './routes/customer-prices/setup'

const StockInRoute = StockInRouteImport.update({
  id: '/stock-in',
  path: '/stock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoriesRoute = FactoriesRouteImport.update({
  id: '/factories',
  path: '/factories',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPricesRoute = CustomerPricesRouteImport.update({
  id: '/customer-prices',
  path: '/customer-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPricesSetupRoute = CustomerPricesSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => CustomerPricesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer-prices': typeof CustomerPricesRouteWithChildren
  '/customers': typeof CustomersRoute
  '/debts': typeof DebtsRoute
  '/exports': typeof ExportsRoute
  '/factories': typeof FactoriesRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-in': typeof StockInRoute
  '/customer-prices/setup': typeof CustomerPricesSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-prices': typeof CustomerPricesRouteWithChildren
  '/customers': typeof CustomersRoute
  '/debts': typeof DebtsRoute
  '/exports': typeof ExportsRoute
  '/factories': typeof FactoriesRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-in': typeof StockInRoute
  '/customer-prices/setup': typeof CustomerPricesSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer-prices': typeof CustomerPricesRouteWithChildren
  '/customers': typeof CustomersRoute
  '/debts': typeof DebtsRoute
  '/exports': typeof ExportsRoute
  '/factories': typeof FactoriesRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-in': typeof StockInRoute
  '/customer-prices/setup': typeof CustomerPricesSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer-prices'
    | '/customers'
    | '/debts'
    | '/exports'
    | '/factories'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-in'
    | '/customer-prices/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-prices'
    | '/customers'
    | '/debts'
    | '/exports'
    | '/factories'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-in'
    | '/customer-prices/setup'
  id:
    | '__root__'
    | '/'
    | '/customer-prices'
    | '/customers'
    | '/debts'
    | '/exports'
    | '/factories'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-in'
    | '/customer-prices/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerPricesRoute: typeof CustomerPricesRouteWithChildren
  CustomersRoute: typeof CustomersRoute
  DebtsRoute: typeof DebtsRoute
  ExportsRoute: typeof ExportsRoute
  FactoriesRoute: typeof FactoriesRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  StockInRoute: typeof StockInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-in': {
      id: '/stock-in'
      path: '/stock-in'
      fullPath: '/stock-in'
      preLoaderRoute: typeof StockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factories': {
      id: '/factories'
      path: '/factories'
      fullPath: '/factories'
      preLoaderRoute: typeof FactoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-prices': {
      id: '/customer-prices'
      path: '/customer-prices'
      fullPath: '/customer-prices'
      preLoaderRoute: typeof CustomerPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-prices/setup': {
      id: '/customer-prices/setup'
      path: '/setup'
      fullPath: '/customer-prices/setup'
      preLoaderRoute: typeof CustomerPricesSetupRouteImport
      parentRoute: typeof CustomerPricesRoute
    }
  }
}

interface CustomerPricesRouteChildren {
  CustomerPricesSetupRoute: typeof CustomerPricesSetupRoute
}

const CustomerPricesRouteChildren: CustomerPricesRouteChildren = {
  CustomerPricesSetupRoute: CustomerPricesSetupRoute,
}

const CustomerPricesRouteWithChildren = CustomerPricesRoute._addFileChildren(
  CustomerPricesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerPricesRoute: CustomerPricesRouteWithChildren,
  CustomersRoute: CustomersRoute,
  DebtsRoute: DebtsRoute,
  ExportsRoute: ExportsRoute,
  FactoriesRoute: FactoriesRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  StockInRoute: StockInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
